# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170208_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 11, 30, 57, 756693, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
