# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170209_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 22, 1, 9, 240990, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
