# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name/model')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('recommended', models.BooleanField(default=False)),
                ('additional_spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base Product',
                'db_table': 'products',
                'verbose_name_plural': 'Base Products',
            },
        ),
        migrations.CreateModel(
            name='GraphicCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name/model')),
                ('manufacturer', models.CharField(choices=[('Nvidia', 'Nvidia'), ('AMD', 'AMD')], max_length=30)),
                ('additional_spec', models.CharField(max_length=30, verbose_name='Additional specifications')),
            ],
            options={
                'verbose_name': 'Graphic card',
                'db_table': 'graphic_card',
                'verbose_name_plural': 'Graphic cards',
            },
        ),
        migrations.CreateModel(
            name='LaptopManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'db_table': 'laptop_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Order number')),
                ('shipping_address', models.TextField(verbose_name='Shipping Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'db_table': 'orders',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='baseshop.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'db_table': 'order_items',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='PhoneManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'db_table': 'phone_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name/model')),
                ('clock_frequency', models.CharField(max_length=30, verbose_name='Clock frequency')),
                ('additional_spec', models.CharField(max_length=30, verbose_name='Additional specifications')),
            ],
            options={
                'verbose_name': 'Processor',
                'db_table': 'processor',
                'verbose_name_plural': 'Processors',
            },
        ),
        migrations.CreateModel(
            name='ProcessorManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'db_table': 'processor_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='TVManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'db_table': 'tv_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseshop.BaseProduct')),
                ('ram', models.CharField(max_length=30, verbose_name='RAM')),
                ('disk', models.CharField(max_length=30, verbose_name='Disk')),
                ('graphic_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseshop.GraphicCard', verbose_name='Graphic card')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseshop.LaptopManufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Laptop',
                'db_table': 'laptop',
                'verbose_name_plural': 'Laptops',
            },
            bases=('baseshop.baseproduct',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseshop.BaseProduct')),
                ('diagonal', models.CharField(max_length=30, verbose_name='Diagonal')),
                ('resolution', models.CharField(max_length=30, verbose_name='Resolution')),
                ('ram', models.CharField(max_length=30, verbose_name='RAM')),
                ('system', models.CharField(max_length=30, verbose_name='System')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseshop.PhoneManufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Phone',
                'db_table': 'phone',
                'verbose_name_plural': 'Phones',
            },
            bases=('baseshop.baseproduct',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseshop.BaseProduct')),
                ('diagonal', models.CharField(help_text='[inch]', max_length=30, verbose_name='Diagonal')),
                ('resolution', models.CharField(choices=[('1366 x 768', 'HD'), ('1920 x 1080', 'Full HD'), ('3840 x 2160', 'Ultra HD 4K')], max_length=30, verbose_name='Resolution')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseshop.TVManufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'TV',
                'db_table': 'tv',
                'verbose_name_plural': 'TVs',
            },
            bases=('baseshop.baseproduct',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='processor',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseshop.ProcessorManufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseshop.BaseProduct', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_baseshop.baseproduct_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='phone',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseshop.Processor', verbose_name='Processor'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseshop.Processor', verbose_name='Processor'),
        ),
    ]
