# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='diagonal',
            field=models.CharField(default=15.6, max_length=30, verbose_name='Diagonal'),
            preserve_default=False,
        ),
    ]
