# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseshop', '0002_laptop_diagonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiccard',
            name='additional_spec',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Additional specifications'),
        ),
        migrations.AlterField(
            model_name='graphiccard',
            name='manufacturer',
            field=models.CharField(choices=[('Nvidia', 'Nvidia'), ('AMD', 'AMD'), ('Intel', 'Intel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='processor',
            name='additional_spec',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Additional specifications'),
        ),
    ]
