# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseshop', '0003_auto_20170208_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
